title: "Anthony Toure — Data Engineering"
description: "Portfolio personnel présentant mes projets en Data Engineering, SQL et développement Full-Stack."
baseurl: ""
url: ""
markdown: kramdown
theme: null
plugins: []
defaults:
  - scope: { path: "" }
    values:
      layout: default
author: "Anthony Toure"
github_username: "Neural-Tony"
exclude:
  - "README.md"
